# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e8ba59315d5e21230db38a28b65f03afc95a5136b1ff3719c9c5ec088820755d5776261b1f1d008a97eedc5d2927a2af009ff8fccba00af884a53509b335692

test:
  secret_key_base: 17970f034ba979f744f47a54687d63ba681a83f1efbb7659a0e63ba079b966486a154cd9f1cfa170041af2a9411fbb5bc422119212ec11b5622abb7de4efe34e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
