# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: setting.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "grpc.Setting" do
    optional :mid, :string, 1
    optional :payment_type, :string, 2
    optional :provider, :string, 3
    optional :payout_type, :string, 4
    optional :begin_date, :string, 5
    optional :end_date, :string, 6
  end
  add_message "grpc.Result" do
    optional :success, :bool, 1
    optional :message, :string, 2
  end
end

module Grpc
  Setting = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.Setting").msgclass
  Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.Result").msgclass
end
