#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


module Thrift
  class Setting
    include ::Thrift::Struct, ::Thrift::Struct_Union
    MID = 1
    PAYMENT_TYPE = 2
    PROVIDER = 3
    PAYOUT_TYPE = 4
    BEGIN_DATE = 5
    END_DATE = 6

    FIELDS = {
      MID => {:type => ::Thrift::Types::STRING, :name => 'mid'},
      PAYMENT_TYPE => {:type => ::Thrift::Types::STRING, :name => 'payment_type'},
      PROVIDER => {:type => ::Thrift::Types::STRING, :name => 'provider'},
      PAYOUT_TYPE => {:type => ::Thrift::Types::STRING, :name => 'payout_type'},
      BEGIN_DATE => {:type => ::Thrift::Types::STRING, :name => 'begin_date'},
      END_DATE => {:type => ::Thrift::Types::STRING, :name => 'end_date'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 1
    MESSAGE = 2

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::BOOL, :name => 'success'},
      MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end
