# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: setting.proto for package 'grpc'

require 'grpc'

module Grpc
  module SettingService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'grpc.SettingService'

      rpc :CreateSetting, Setting, Result
      rpc :UpdateSetting, Setting, Result
    end

    Stub = Service.rpc_stub_class
  end
end
